### ISSUE TITLE
Syntax error when running example code

### ISSUE THREAD

**Issue by EMerckx** [ZeusWPI/aichallenge#25]
Hello Zeus

I have tried to run the the arbiter with the test.json configuration, but I'm always getting syntax errors. Apparently the other members of my team don't have this issue. I've added the error output below.

    $ python3.5 arbiter.py test.json
    
    Traceback (most recent call last):
      File "../testbots/destroybot.py", line 83, in <module>
        game = Game(sys.argv[1])
      File "../testbots/destroybot.py", line 34, in __init__
        self.parse_input()
      File "../testbots/destroybot.py", line 37, in parse_input
        self.parse_forts()
      File "../testbots/destroybot.py", line 42, in parse_forts
        for i in range(int(input().split()[0])):
      File "<string>", line 1
        6 forts:
              ^
    SyntaxError: invalid syntax
      File "../testbots/testrobot.py", line 144
        def orders(self) -> str:
                         ^
    SyntaxError: invalid syntax

Before running the example code, I've just installed Python 3.5.1 on my linux machine (elementary OS), which you can clearly see in the output below.

    $ python3.5 --version
    Python 3.5.1

Is there something that I'm forgetting? (I'm quite new to Python)

Sincerely yours,
Ewout

**Comment by Procrat** [comment]
Hi Ewout!

First of all, thanks for your enthousiasm to participate!
I think the "problem" is that elementary OS uses Python 2 by default and the test bots in the repo are written in Python 3. In `test.json` the command to run them is `python` which on your machine is probably aliased to `python2` and on your friends' machines to `python3`.

I've changed the `test.json` file to explicitely use Python 3 now. Could you pull in the latest changes of the repo and try again? ^_^

Cheers!

**Comment by EMerckx** [comment]
Hello Procrat

I see now what the problem is! Thank you for solving it. The `test.json` and `wow.json` configurations don't give these problems anymore. But it seems there is still a minor issue, I'll paste the output below.

    $ python3.5 arbiter.py test.json 
    /* steps */
    Made step 12
    
    Traceback (most recent call last):
      File "../testbots/testrobot.py", line 206, in <module>
        Game.start()
      File "../testbots/testrobot.py", line 105, in start
        mind.play()
      File "../testbots/testrobot.py", line 138, in play
        self.__collect_data()
      File "../testbots/testrobot.py", line 153, in __collect_data
        self.territory = set(f for f in self.forts if self.__in_safety(f))
      File "../testbots/testrobot.py", line 153, in <genexpr>
        self.territory = set(f for f in self.forts if self.__in_safety(f))
      File "../testbots/testrobot.py", line 201, in __in_safety
        for n in my_fort.neighbours)
      File "../testbots/testrobot.py", line 201, in <genexpr>
        for n in my_fort.neighbours)
    KeyError: 'neutral'
    
    Made step 13
    /* steps */
    Made step 500
    Succes!
    
    Traceback (most recent call last):
      File "../testbots/destroybot.py", line 83, in <module>
        game = Game(sys.argv[1])
      File "../testbots/destroybot.py", line 34, in __init__
        self.parse_input()
      File "../testbots/destroybot.py", line 37, in parse_input
        self.parse_forts()
      File "../testbots/destroybot.py", line 42, in parse_forts
        for i in range(int(input().split()[0])):
    EOFError: EOF when reading a line

I also get the EOFError while executing the `wow.json` example.

Do you know what's the problem here?

Sincerely yours,
Ewout

**Comment by R13N** [comment]
The `EOFError` is normal. This is the result of the arbiter closing the stream to destroybot when the game is finished.

**Comment by SirDestrox** [comment]
Fixed in 079981d56657a751afa3763ba99b3d5e32221e71
