### ISSUE TITLE
cannot run test.json

### ISSUE THREAD

**Issue by KennethVerbeure** [ZeusWPI/aichallenge#92]
I get an error in the arbiter when running the test case

**Comment by KennethVerbeure** [comment]
python arbiter.py test.json                                                                                                                                                                                                  (venv) 
Traceback (most recent call last):
  File "arbiter.py", line 536, in <module>
    loop.run_until_complete(game.play_async())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "arbiter.py", line 468, in play_async
    self.step()
  File "arbiter.py", line 510, in step
    fort.step()
  File "arbiter.py", line 227, in step
    self.resolve_siege()
  File "arbiter.py", line 253, in resolve_siege
    winner.capture(self)
AttributeError: 'NoneType' object has no attribute 'capture'

**Comment by NoctuaNivalis** [comment]
I've seen this bug quite often indeed, every time my bot timed out. Might be other causes as well, though.
